# -*- coding: utf-8 -*-
# 2024 Moval Agroingeniería
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

{
    "name": "Water Users Association: CAYC General Management",
    "summary": "CAYC general management of base water users association",
    "description": "Includes management for primary and che partners / parcels"
                   " and base WUA entities",
    "version": '10.0.1.1.0',
    "category": "Water Users Associations",
    "website": "http://www.moval.es",
    "author": "Moval Agroingeniería",
    "license": "AGPL-3",
    "depends": [
        "base_wua_cayc",
        "base_wua_crop_planning",
        "base_wua_gravity_irrigation",
        "base_wua_irrigation_report",
        "base_wua_pressurized_irrigation_request",
        "base_wua_infrastructure_pressurized_hierarchy",
        "base_wua_quota_management",
        "wua_pressurized_irrigation_request_sinema",
        "base_wua_assembly",
        "base_wua_invoicing",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/res_partner_cron.xml",
        "data/wua_preswateringrequest_change_state_cron.xml",
        "data/wua_wuabase_data.xml",
        "data/wua_preswatering_issue_cron.xml",
        "data/wua_octroi_data.xml",
        "data/wua_waterchannel_data.xml",
        "reports/wua_parcel_report.xml",
        "reports/wua_partner_report.xml",
        "views/resources.xml",
        "views/wua_irrigation_menus_view.xml",
        "views/wua_irrigation_configuration_view.xml",
        "views/wua_cropplan_view.xml",
        "views/wua_presconsumption_view.xml",
        "views/wua_presresconsumption_view.xml",
        "views/wua_preswateringperiod_view.xml",
        "views/wua_preswatering_view.xml",
        "views/wua_preswateringrequest_view.xml",
        "views/wua_reading_view.xml",
        "views/wua_negative_reading_view.xml",
        "views/wua_watermeter_view.xml",
        "views/res_partner_view.xml",
        "views/wua_parcel_view.xml",
        "views/wua_intake_view.xml",
        "views/wua_wuabase_view.xml",
        "views/wua_octroi_view.xml",
        "views/wua_waterchannel_view.xml",
    ],
    'qweb': [
        'static/src/xml/base.xml',
    ],
    "installable": True,
    "application": False,
}
