# -*- coding: utf-8 -*-
# 2025 Moval Agroingeniería
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

{
    "name": "Water Users Association: Irrigation Recommendations",
    "summary": "In a water users association, calculation of the "
               "irrigation recommendations",
    "version": '10.0.1.1.0',
    "category": "Water Users Associations",
    "website": "http://www.moval.es",
    "author": "Moval Agroingeniería",
    "license": "AGPL-3",
    "depends": [
        "wua_remotesensing_sentinelhub_ndvi",
        "remotecontrol_siar",
        "wua_mdm_sensor_management",
        # "base_wua_portal_sensorreading",
        "base_wua_sigpac",
        "web_widget_bokeh_chart",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/wua_cropfamily_data.xml",
        "data/wua_monitoringperiod_calculation_cron.xml",
        "wizard/wizard_activate_season_view.xml",
        "wizard/wizard_base_wua_hydric_estimation.xml",
        "wizard/wizard_import_kml_view.xml",
        "wizard/wizard_cropunit_creation_summary_view.xml",
        "views/resources.xml",
        "views/base_wua_hydric_estimation_menus.xml",
        "views/wua_cultivation_menu_duplicate.xml",
        "views/wua_irrigation_config_settings_view.xml",
        "views/wua_irrigationsystem_view.xml",
        "views/wua_cropfamily_view.xml",
        "views/wua_cultivation_view.xml",
        "views/wua_cropunit_view.xml",
        "views/wua_cropunit_vegetationindex_ndvi_view.xml",
        "views/wua_parcel_cropunit_ndvi_actions.xml",
        "views/wua_monitoringperiod_view.xml",
        "views/wua_recommendationperiod_view.xml",
        "views/wua_hydricneed_view.xml",
        "views/wua_parcel_view.xml",
        "views/wua_parcel_sigpaclink_actions.xml",
        "views/wua_agriculturalseason_view.xml",
        "wizard/wizard_generate_monitoringperiods_view.xml",
        "reports/wua_hydricneed_report.xml",
        "data/wua_hydricneed_email_template.xml",
        "data/wua_calculation_notification_email_template.xml",
    ],
    "installable": True,
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
    "uninstall_hook": "uninstall_hook",
    "application": False,
}
