# -*- coding: utf-8 -*-
# 2020 Moval Agroingeniería
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

{
    "name": "Water Users Association Infrastructure (C.G.R. Abarán)",
    "summary": "Moval-Regadío customization for C.G.R. Abarán",
    "version": '10.0.1.1.1',
    "category": "Water Users Associations",
    "website": "http://www.moval.es",
    "author": "Moval Agroingeniería",
    "license": "AGPL-3",
    "depends": [
        "base_wua",
        "base_wua_irrigation_measurement",
        "base_wua_invoicing_pressurized_irrigation",
        "base_wua_invoicing_gravity_irrigation",
        "base_wua_invoicing_irrigation_report",
        "base_wua_invoicing_separate_parcel_billing",
        "account_banking_debit_atrm",
        "account_invoice_report_due_list",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/wua_agriculturalseason_view.xml",
        "views/wua_parcel_view.xml",
        "views/res_partner_view.xml",
        "views/wua_config_settings_view.xml",
        "views/resources.xml",
        "views/wua_irrigation_config_settings_view.xml",
        "views/wua_flowreading_view.xml",
        "views/wua_flowmeter_view.xml",
        "views/wua_intakeconsumption_view.xml",
        "views/wua_negative_flowreading_view.xml",
        "views/wua_intake_view.xml",
        "views/wua_presconsumption_view.xml",
        "views/wua_irrigationreport_view.xml",
        "views/wua_waterconnection_view.xml",
        "views/wua_invoiceset_view.xml",
        "reports/wua_partner_report.xml",
        "reports/wua_sum_intakeconsumption_invoicing_report.xml",
        "reports/report_invoice.xml",
    ],
    'qweb': ['static/src/xml/button_import_flowreadings.xml'],
    "installable": True,
    "application": False,
}
