# -*- coding: utf-8 -*-
# Copyright 2017 Eduardo Iniesta - <einiesta@moval.es>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

{
    "name": "Water Users Association Invoicing",
    "summary": "In a water users association, global invoicing "
               "based on a selection of items (parcels, partners, etc)",
    "version": '10.0.1.1.3',
    "category": "Water Users Associations",
    "website": "http://www.moval.es",
    "author": "Moval Agroingeniería",
    "license": "AGPL-3",
    "depends": [
        "base_wua",
        "base_wua_infrastructure",
        "account_cancel",
        "account_banking_sepa_direct_debit_extended",
        "sale",
        "account_invoice_transmit_method",
        "account_invoice_line_report",
        "account_due_list",
        "account_due_list_aging_comments",
        "account_due_list_days_overdue",
        "account_due_list_payment_mode",
        "account_credit_control_dunning_fees",
        "account_analytic_default",
        "account_payment_return",
        "account_invoice_analytic_search",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/product_category_data.xml",
        "data/wua_invoicing_config_settings_data.xml",
        "reports/report_credit_control_summary.xml",
        "reports/report_invoice.xml",
        "reports/wua_partner_invoice_lines.xml",
        "views/resources.xml",
        "views/product_views.xml",
        "views/wua_invoiceset_view.xml",
        "views/wua_invoicing_config_settings_view.xml",
        "views/account_invoice_view.xml",
        "views/wua_parcel_view.xml",
        "views/wua_waterconnection_view.xml",
        "views/wua_irrigationgate_view.xml",
        "views/wua_irrigationditch_view.xml",
        "views/wua_irrigationshed_view.xml",
        "views/wua_hydraulicsector_view.xml",
        "views/res_partner_view.xml",
        "views/account_view.xml",
        "wizard/wizard_print_partner_invoices_lines_views.xml",
        "wizard/res_partner_archive_wizard_view.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
}
