from . import maintenance_equipmenttag
from . import maintenance_equipment_category
from . import wua_infrastructureitem
from . import wua_intake
from . import wua_drainageditch
from . import wua_flowdivider
from . import wua_flowmeter
from . import wua_irrigationditch
from . import wua_irrigationgate
from . import wua_irrigationshed
from . import wua_photovoltaicplant
from . import wua_pressuresensor
from . import wua_pumpgroup
from . import wua_pumpunit
from . import wua_reservoir
from . import wua_waterconnection
from . import wua_watermeter
from . import wua_waterpipe
from . import wua_airvalve
from . import wua_drainagevalve
from . import wua_filteringstation
from . import wua_valve
from . import maintenance
from . import maintenance_kind
from . import maintenance_request
from . import maintenance_team
from . import maintenance_settings
from . import maintenance_stage
from . import maintenance_plan
from . import wua_building
from . import wua_processingcentre
from . import wua_powerline
from . import wua_powerlinesupport
from . import mdm_measurement_device
from . import wua_tertiarypipe
from . import wua_irrigationstretch
