# -*- coding: utf-8 -*-
# 2020 Moval Agroingeniería
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

{
    "name": "Water Users Association: Quota Management",
    "summary": "Quota management for pressurized irrigation, gravity "
               "irrigation and irrigation based on irrigation reports",
    "version": '10.0.1.1.2',
    "category": "Water Users Associations",
    "website": "http://www.moval.es",
    "author": "Moval Agroingeniería",
    "license": "AGPL-3",
    "depends": [
        "base_wua_invoicing_pressurized_irrigation",
        "base_wua_invoicing_gravity_irrigation",
        "base_wua_invoicing_irrigation_report",
        "web_widget_bokeh_chart",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/mail_template_data.xml",
        "data/wua_quotas_config_settings_data.xml",
        "data/wua_superproduct_data.xml",
        "data/wua_individualinput_category_data.xml",
        "data/wua_parcel_refreshflag_cron.xml",
        "data/wua_cession_cron.xml",
        "wizard/wizard_generate_quotaperiods_view.xml",
        "wizard/wizard_set_activeagriculturalseason_view.xml",
        "wizard/wizard_recalculate_quotas_view.xml",
        "wizard/wizard_massive_individualinputs_view.xml",
        "wizard/wizard_provision_parcel_view.xml",
        "wizard/wizard_provision_partner_view.xml",
        "wizard/wizard_massive_compensatorytransfers_view.xml",
        "views/resources.xml",
        "views/base_wua_quota_management_menus.xml",
        "views/wua_quotas_config_settings_view.xml",
        "views/product_views.xml",
        "views/wua_superproduct_view.xml",
        "views/wua_agriculturalseason_view.xml",
        "views/res_partner_view.xml",
        "views/wua_waterconnection_view.xml",
        "views/wua_irrigationshed_view.xml",
        "views/wua_hydraulicsector_view.xml",
        "views/wua_quotaperiod_view.xml",
        "views/wua_quota_view.xml",
        "views/wua_hydricmovement_view.xml",
        "views/wua_superproduct_dashboard_view.xml",
        "views/wua_individualinput_view.xml",
        "views/wua_cession_view.xml",
        "views/wua_individualinput_category_view.xml",
        "views/wua_presconsumption_view.xml",
        "views/wua_gravconsumption_view.xml",
        "views/wua_wateringrequest_view.xml",
        "views/wua_irrigationreport_view.xml",
        "views/wua_parcel_view.xml",
        "views/wua_infrastructure_config_settings_view.xml",
        "reports/wua_partner_quota_report.xml",
        "reports/wua_partner_quota_cession_report.xml",
        "reports/wua_partner_quota_individualinput_report.xml",
        "reports/wua_waterconnection_readings_report.xml",
    ],
    "external_dependencies": {
        "python": ["numpy", "bokeh"]},
    "post_init_hook": "post_init_hook",
    "uninstall_hook": "uninstall_hook",
    "installable": True,
    "application": True,
}
