# -*- coding: utf-8 -*-
# Copyright 2017 Eduardo Iniesta - <einiesta@moval.es>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

{
    "name": "Water Users Association Management",
    "summary": "In a water users association, management of users "
               "and parcels",
    "version": '10.0.1.1.2',
    "category": "Water Users Associations",
    "website": "http://www.moval.es",
    "author": "Moval Agroingeniería",
    "license": "AGPL-3",
    "depends": [
        "base",
        "web",
        "web_fix_chrome_web_client",
        "web_fix_mobile_back_button",
        "base_setup",
        "mail",
        "mass_mailing",
        "mass_mailing_partner",
        "mail_tracking_mass_mailing",
        "document",
        "mass_editing",
        "partner_address_street_number",
        "web_tree_many2one_clickable",
        "partner_second_lastname",
        "web_searchbar_full_width",
        "account_wua",
        "l10n_es",
        "account_accountant",
        "l10n_es_partner",
        "l10n_es_toponyms",
        "account_banking_mandate",
        "web_widget_image_download",
        "web_dialog_size",
        "web_listview_invert_selection",
        "portal",
        "portal_sale",
        "dev_export_excel",
        "web_favicon",
        "web_tree_dynamic_colored_field",
        "base_wua_report",
        "l10n_es_partner_address_street_type",
        "fontawesome_ext",
        "base_extra_attachment",
        "html_field_in_tree_view",
        "report_qr",
        "web_domain_field",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/wua_region_data.xml",
        "data/wua_config_settings_data.xml",
        "data/wua_irrigationsystem_data.xml",
        "data/wua_productionmethod_data.xml",
        "data/wua_subparceltype_data.xml",
        "data/wua_cultivation_data.xml",
        "data/wua_sequences.xml",
        "data/wua_parcel_cron.xml",
        "wizard/wizard_change_parcel_name_view.xml",
        "views/resources.xml",
        "views/wua_parcel_view.xml",
        "views/wua_region_view.xml",
        "views/wua_config_settings_view.xml",
        "views/wua_mastertable_view.xml",
        "views/wua_waterreservoir_view.xml",
        "views/wua_rurallocation_view.xml",
        "views/wua_concession_view.xml",
        "views/wua_irrigationsystem_view.xml",
        "views/wua_productionmethod_view.xml",
        "views/wua_subparceltype_view.xml",
        "views/wua_cultivationplan_view.xml",
        "views/wua_farmproperty_view.xml",
        "views/wua_cultivation_view.xml",
        "views/wua_parceltag_view.xml",
        "views/wua_parceltag_view.xml",
        "views/res_partner_view.xml",
        "views/res_partner_bank_view.xml",
        "views/res_users_view.xml",
        "reports/account_report.xml",
        "reports/wua_partner_report.xml",
        "reports/wua_parcel_report.xml",
        "reports/wua_partner_report_consent.xml",
        "reports/wua_tenant_report.xml",
        "reports/wua_lessor_report.xml",
    ],
    "installable": True,
    "application": True,
}
