{
 "title": "pumpgroup-integration",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "postgres" },
   {
    "name": "pumpgroup",
    "label": "Bombeo",
    "query": "SELECT DISTINCT name FROM wua_pumpgroup;"
   }
  ]
 },
 "panels": [
  { "title": "Datos por Bombeo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Caudal",
   "type": "timeseries",
   "description": "Caudal ${pumpgroup}",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m³/h" } },
   "targets": [
    {
     "rawSql": "    SELECT measurement.measurement_time AS \"time\",\n           pumpgroup.name AS \"Bombeo\",\n           measurement.instantaneous_flow AS \"Caudal\"\n      FROM wua_pumpgroupmeasurement measurement\nINNER JOIN wua_pumpgroup pumpgroup ON measurement.pumpgroup_id = pumpgroup.id\n     WHERE pumpgroup.name IN ($pumpgroup)\n       AND measurement.of_active_agriculturalseason\n  GROUP BY \"time\", pumpgroup.name, measurement.instantaneous_flow\n  ORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Potencia consumida",
   "type": "timeseries",
   "description": "Potencia consumida ${pumpgroup}",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "    SELECT measurement.measurement_time AS \"time\",\n           pumpgroup.name AS \"Bombeo\",\n           measurement.consumed_power AS \"Potencia consumida\"\n      FROM wua_pumpgroupmeasurement measurement\nINNER JOIN wua_pumpgroup pumpgroup ON measurement.pumpgroup_id = pumpgroup.id\n     WHERE pumpgroup.name IN (${pumpgroup})\n       AND measurement.of_active_agriculturalseason\n  GROUP BY \"time\", pumpgroup.name,measurement.consumed_power\n  ORDER BY \"time\";"
    }
   ]
  },
  {
   "title": "Altura manométrica",
   "type": "timeseries",
   "description": "Altura manométrica $bombeo",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mca" } },
   "targets": [
    {
     "rawSql": "    SELECT measurement.measurement_time AS \"time\", pumpgroup.name AS \"Bombeo\", measurement.manometric_height AS \"Altura manométrica\"\n      FROM wua_pumpgroupmeasurement measurement\nINNER JOIN wua_pumpgroup pumpgroup ON measurement.pumpgroup_id = pumpgroup.id\n     WHERE pumpgroup.name IN ($pumpgroup)\n       AND measurement.of_active_agriculturalseason\n       AND $__timeFilter(measurement.measurement_time)\n  GROUP BY pumpgroup.name, measurement.manometric_height, measurement.measurement_time\n  ORDER BY measurement.measurement_time"
    }
   ]
  },
  {
   "title": "Presión de impulsión",
   "type": "timeseries",
   "description": "Presión de impulsión $bombeo",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mca" } },
   "targets": [
    {
     "rawSql": "    SELECT measurement.measurement_time AS \"time\", pumpgroup.name AS \"Bombeo\", measurement.impulsion_pressure AS \"Presión de impulsión\"\n      FROM wua_pumpgroupmeasurement measurement\nINNER JOIN wua_pumpgroup pumpgroup ON measurement.pumpgroup_id = pumpgroup.id\n     WHERE pumpgroup.name IN ($pumpgroup)\n       AND measurement.of_active_agriculturalseason\n       AND $__timeFilter(measurement.measurement_time)\n  GROUP BY pumpgroup.name, measurement.impulsion_pressure, measurement.measurement_time\n  ORDER BY measurement.measurement_time"
    }
   ]
  },
  {
   "title": "Presión de aspiración",
   "type": "timeseries",
   "description": "Presión de aspiración $bombeo",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mca" } },
   "targets": [
    {
     "rawSql": "    SELECT measurement.measurement_time AS \"time\", pumpgroup.name AS \"Bombeo\", measurement.suction_pressure AS \"Presión de aspiración\"\n      FROM wua_pumpgroupmeasurement measurement\nINNER JOIN wua_pumpgroup pumpgroup ON measurement.pumpgroup_id = pumpgroup.id\n     WHERE pumpgroup.name IN ($pumpgroup)\n       AND measurement.of_active_agriculturalseason\n       AND $__timeFilter(measurement.measurement_time)\n  GROUP BY pumpgroup.name, measurement.suction_pressure, measurement.measurement_time\n  ORDER BY measurement.measurement_time"
    }
   ]
  },
  {
   "title": "Eficiencia energética",
   "type": "timeseries",
   "description": "Eficiencia energética $bombeo",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "    SELECT measurement.measurement_time AS \"time\", pumpgroup.name AS \"Bombeo\", measurement.energy_efficiency AS \"Eficiencia energética\"\n      FROM wua_pumpgroupmeasurement measurement\nINNER JOIN wua_pumpgroup pumpgroup ON measurement.pumpgroup_id = pumpgroup.id\n     WHERE pumpgroup.name IN ($pumpgroup)\n       AND measurement.of_active_agriculturalseason\n  GROUP BY \"time\", pumpgroup.name, measurement.energy_efficiency\n  ORDER BY \"time\"\n"
    }
   ]
  },
  { "title": "Datos Globales", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Energía consumida por Bombeo",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "    SELECT pumpgroup.name AS \"Bombeo\", sum(measurement.consumed_energy) AS \"Energía consumida\"\n      FROM wua_pumpgroupmeasurement measurement\nINNER JOIN wua_pumpgroup pumpgroup ON measurement.pumpgroup_id = pumpgroup.id\n     WHERE measurement.of_active_agriculturalseason\n  GROUP BY pumpgroup.name\n  ORDER BY pumpgroup.name"
    }
   ]
  },
  {
   "title": "Energía consumida por categoría",
   "type": "piechart",
   "description": "Energía consumida por categoría $bombeo",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "    SELECT measurement.energy_efficiency_rating AS \"Categoría\", sum(measurement.consumed_energy) AS \"Energía consumida\"\n      FROM wua_pumpgroupmeasurement measurement\nINNER JOIN wua_pumpgroup pumpgroup ON measurement.pumpgroup_id = pumpgroup.id\n     WHERE pumpgroup.name IN ($bombeo)\n       AND measurement.of_active_agriculturalseason\n  GROUP BY measurement.energy_efficiency_rating\n  ORDER BY measurement.energy_efficiency_rating"
    }
   ]
  }
 ]
}