# -*- coding: utf-8 -*-
# 2024 Moval Agroingeniería
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

{
    "name": "Pressurized Irrigation Management for Water Users Associations",
    "summary": "In a water users association, management of the "
               "pressurized irrigation",
    "version": '10.0.1.1.8',
    "category": "Water Users Associations",
    "website": "http://www.moval.es",
    "author": "Moval Agroingeniería",
    "license": "AGPL-3",
    "depends": [
        "base_action_rule",
        "wua_structure_irrigation",
    ],
    "data": [
        "security/ir.model.access.csv",
        "wizard/wizard_remove_readings_view.xml",
        "wizard/wizard_edit_reading_time_view.xml",
        "wizard/wizard_generate_estimated_readings_view.xml",
        "data/wua_irrigation_config_settings_data.xml",
        "data/wua_negative_reading_notice_mail.xml",
        "data/wua_negative_reading_notice_action.xml",
        "views/resources.xml",
        "views/res_partner_view.xml",
        "views/wua_watermeter_view.xml",
        "views/wua_waterconnection_view.xml",
        "views/wua_reading_view.xml",
        "views/wua_presconsumption_view.xml",
        "views/wua_pressuresensor_view.xml",
        "views/wua_pressuresensormeasurement_view.xml",
        "views/wua_parcel_view.xml",
        "views/wua_agriculturalseason_view.xml",
        "views/wua_negative_reading_view.xml",
        "views/wua_irrigation_config_settings_view.xml",
        "views/wua_infrastructure_config_settings_view.xml",
        "views/wua_waterconnection_irrigation_schedule_view.xml",
        "views/wua_waterconnection_irrigation_event_view.xml",
        "views/wua_waterconnection_irrigation_shift_view.xml",
        "views/wua_irrigationshed_view.xml",
        "views/wua_zone_view.xml",
        "views/wua_tertiarypipe_view.xml",
        "reports/wua_parcel_report.xml",
        "reports/wua_watermeter_report.xml",
        "data/wua_infrastructure_config_settings_data.xml",
        "wizard/wizard_print_readings_view.xml",
        "reports/wua_waterconnection_readings_report.xml",
        "views/wua_waterconnection_state_view.xml",
        "data/wua_waterconnection_state_data.xml",
    ],
    "installable": True,
    "application": True,
}
