# -*- coding: utf-8 -*-
# 2023 Moval Agroingeniería
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

{
    "name": "Water Users Association: Maintenance",
    "summary": " In a water users association, maintenance helper of the "
               " entire set of WUA infrastructure.",
    "version": '10.0.1.1.10',
    "category": "Water Users Associations",
    "website": "http://www.moval.es",
    "author": "Moval Agroingeniería",
    "license": "AGPL-3",
    "depends": [
        "hr_maintenance",
        "base_maintenance_config",
        "maintenance_plan",
        "maintenance_form_buttons",
        "base_wua_infrastructure",
        "base_wua_pressurized_irrigation",
        "base_wua_infrastructure_pressurized_hierarchy",
        "base_wua_infrastructure_gravity_hierarchy",
        "base_wua_infrastructure_primary",
        "base_wua_reservoir",
        "base_wua_infrastructure_pump",
        "base_wua_infrastructure_energy",
        "wua_mdm_sensor_management",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/maintenance_config_settings_data.xml",
        "data/maintenance_equipment_category_data.xml",
        "data/maintenance_kinds_data.xml",
        "data/maintenance_request_cron.xml",
        "data/maintenance_cron.xml",
        "data/maintenance_request_notify_action.xml",
        "data/maintenance_request_notify_rule.xml",
        "wizard/wizard_massive_maintenance_requests.xml",
        "wizard/wizard_image_preview.xml",
        "views/maintenance_equipment_view.xml",
        "views/maintenance_views.xml",
        "views/maintenance_plan_view.xml",
        "views/maintenance_settings_view.xml",
        "views/maintenance_request_view.xml",
        "views/maintenance_kind_views.xml",
        "views/maintenance_stage_views.xml",
        "views/maintenance_equipment_category_view.xml",
        "views/menuitems.xml",
        "views/resources.xml",
        "reports/maintenance_request_report.xml",
    ],
    "installable": True,
    "post_init_hook": "post_init_hook",
    "application": False,
}
